spring:
  profiles: prd
  datasource:
    username: saga
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.servicecomb.io:3306/saga
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
